### ISSUE TITLE
Hot code reloading?

### ISSUE THREAD

**Issue by paulreimer** [OtoloNetworks/rebar3_osv#1]
This is a really cool project! I'm using it as part of learning about deploying Erlang.

Could the OSv unikernel concept be compatible with hot code reloading? (I understand it may not be implemented now, just wondering if the concepts could be used together and if there might be a benefit to doing so.)

**Comment by rickpayne** [comment]
Yes, you can use the BEAM hot code reloading. You can either enable the OSv API to upload files, then reload in the BEAM as normal - or on a recent OSv and qemu (5.0?) you may be able to use virtio-fs and replace the files locally, then reload.
I've done the former many times, but not got to the point of trying virtio-fs yet.
What you can't do, is update the OSv kernel whilst its running (which should be reasonably obvious).

**Comment by paulreimer** [comment]
That is so cool! I can't wait to try that.

**Comment by paulreimer** [comment]
Just to check, you use this API (the OSv `file.json` REST API), repeated `POST`s (one for each of the files in the new release):
http://osv.io/api/swagger-ui/dist/index.html#!/file.json

And so your production setup would be running the OSv REST API (presumably with SSL client certificates and bound to a different interface or something?)
